### NBA 2020 Season Analysis
In this project, we'll work with data from the 2020 NBA Season to perform Data Wrangling techniques, and then some analysis.

We'll start by performing some Data Wrangling techniques to join the data from the season with that of players. We'll then perform different modifications and cleaning tasks to make sure our data is ready for analysis.

Finally, we'll perform some analysis to find out deeper about the season.

In [1]:
import pandas as pd

In [134]:
s2020_df = pd.read_csv('nba_2020.csv')

In [135]:
players_df = pd.read_csv('all_seasons.csv')

In [136]:
s2020_df.head()

,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,FTr,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,Steven Adams,C,26,OKC,63,1680,20.5,0.604,0.006,0.421,...,14.2,17.3,3.8,2.7,6.5,0.185,1.9,1.1,2.9,2.1
1,Bam Adebayo,PF,22,MIA,72,2417,20.3,0.598,0.018,0.484,...,17.6,21.2,4.6,3.9,8.5,0.168,1.4,2.0,3.4,3.3
2,LaMarcus Aldridge,C,34,SAS,53,1754,19.7,0.571,0.198,0.241,...,7.8,23.4,3.0,1.4,4.5,0.122,1.8,-0.5,1.4,1.5
3,Kyle Alexander,PF,23,MIA,2,13,4.7,0.500,0.000,0.000,...,33.3,10.2,0.0,0.0,0.0,-0.003,-6.1,-3.5,-9.6,0.0
4,Nickeil Alexander-Walker,SG,21,NOP,47,591,8.9,0.473,0.500,0.139,...,16.1,23.3,-0.7,0.4,-0.2,-0.020,-3.2,-1.4,-4.6,-0.4

In [137]:
players_df.head()

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
0,0,Randy Livingston,HOU,22.0,193.04,94.800728,Louisiana State,USA,1996,2,...,3.9,1.5,2.4,0.3,0.042,0.071,0.169,0.487,0.248,1996-97
1,1,Gaylon Nickerson,WAS,28.0,190.50,86.182480,Northwestern Oklahoma,USA,1994,2,...,3.8,1.3,0.3,8.9,0.030,0.111,0.174,0.497,0.043,1996-97
2,2,George Lynch,VAN,26.0,203.20,103.418976,North Carolina,USA,1993,1,...,8.3,6.4,1.9,-8.2,0.106,0.185,0.175,0.512,0.125,1996-97
3,3,George McCloud,LAL,30.0,203.20,102.058200,Florida State,USA,1989,1,...,10.2,2.8,1.7,-2.7,0.027,0.111,0.206,0.527,0.125,1996-97
4,4,George Zidek,DEN,23.0,213.36,119.748288,UCLA,USA,1995,1,...,2.8,1.7,0.3,-14.1,0.102,0.169,0.195,0.500,0.064,1996-97

### Data Wrangling

##### Merge s2020_df and players_df with a left join

In [138]:
players_df = players_df.loc[players_df['season']=='2019-20']

In [139]:
df = s2020_df.merge(players_df, how='left', left_on='Player', right_on='player_name')

In [140]:
df.head()

,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,FTr,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
0,Steven Adams,C,26,OKC,63,1680,20.5,0.604,0.006,0.421,...,10.9,9.3,2.3,4.4,0.128,0.214,0.168,0.604,0.128,2019-20
1,Bam Adebayo,PF,22,MIA,72,2417,20.3,0.598,0.018,0.484,...,15.9,10.2,5.1,5.0,0.077,0.224,0.212,0.598,0.238,2019-20
2,LaMarcus Aldridge,C,34,SAS,53,1754,19.7,0.571,0.198,0.241,...,18.9,7.4,2.4,-3.2,0.058,0.162,0.236,0.571,0.117,2019-20
3,Kyle Alexander,PF,23,MIA,2,13,4.7,0.500,0.000,0.000,...,1.0,1.5,0.0,-6.7,0.111,0.067,0.079,0.500,0.000,2019-20
4,Nickeil Alexander-Walker,SG,21,NOP,47,591,8.9,0.473,0.500,0.139,...,5.7,1.8,1.9,-3.6,0.015,0.122,0.233,0.473,0.212,2019-20

##### Are there misses (mismatches) in the resulting dataframe?

In [141]:
df['player_name'].isna().any()

True

##### How many rows couldn't be matched?

In [142]:
df['player_name'].isna().sum()

58

##### Extract the names of the players that couldn't be matched

In [143]:
player_misses = list(df.loc[df['player_name'].isna(), 'Player'].unique())
player_misses

['Dāvis Bertāns',
 'Bogdan Bogdanović',
 'Bojan Bogdanović',
 'Brian Bowen',
 'Charlie Brown',
 'Vlatko Čančar',
 'Luka Dončić',
 'Goran Dragić',
 'James Ennis',
 'Cristiano Felício',
 'Melvin Frazier',
 'Michael Frazier',
 'Harry Giles',
 'Juan Hernangómez',
 'Willy Hernangómez',
 'Danuel House',
 'Ersan İlyasova',
 'Wesley Iwundu',
 'B.J. Johnson',
 'Nikola Jokić',
 'Kevin Knox',
 'Skal Labissière',
 'Timothé Luwawu-Cabarrot',
 'Boban Marjanović',
 'Frank Mason III',
 'Nicolò Melli',
 'C.J. Miles',
 'Marcus Morris',
 'Džanan Musa',
 'Sviatoslav Mykhailiuk',
 'Zach Norvell',
 'Jusuf Nurkić',
 'Anžejs Pasečņiks',
 'Otto Porter',
 'Kristaps Porziņģis',
 'J.J. Redick',
 'Luka Šamanić',
 'Dario Šarić',
 'Tomáš Satoranský',
 'Dennis Schröder',
 'Alen Smailagić',
 'J.R. Smith',
 'Jonas Valančiūnas',
 'Nikola Vučević',
 'Lonnie Walker',
 'Derrick Walton',
 'Robert Williams',
 'Ante Žižić']

##### Modify players_df with the correct names to re-try a successful merge

In [155]:
players_df.loc[players_df['player_name'].str.contains('Marcus')]

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
10738,10738,LaMarcus Aldridge,SAS,34.0,210.82,113.398000,University of Texas at Austin,USA,2006,1,...,18.9,7.4,2.4,-3.2,0.058,0.162,0.236,0.571,0.117,2019-20
11103,11103,Marcus Morris Sr.,LAC,30.0,203.20,98.883056,Kansas,USA,2011,1,...,16.7,5.0,1.4,1.5,0.029,0.128,0.216,0.570,0.066,2019-20
11104,11104,Marcus Smart,BOS,26.0,190.50,99.790240,Oklahoma State,USA,2014,1,...,12.9,3.8,4.9,7.3,0.020,0.089,0.183,0.518,0.214,2019-20

In [156]:
     #players_df   :   #s2020_df
player_names_replacements = {
    'Davis Bertans':'Dāvis Bertāns',
    'Bogdan Bogdanovic':'Bogdan Bogdanović',
    'Bojan Bogdanovic':'Bojan Bogdanović',
    'Brian Bowen II':'Brian Bowen',
    'Charlie Brown Jr.':'Charlie Brown',
    'Vlatko Cancar':'Vlatko Čančar',
    'Luka Doncic':'Luka Dončić',
    'Goran Dragic':'Goran Dragić',
    'James Ennis III':'James Ennis',
    'Cristiano Felicio':'Cristiano Felício',
    'Melvin Frazier Jr.':'Melvin Frazier',
    'Michael Frazier II':'Michael Frazier',
    'Harry Giles III':'Harry Giles',
    'Juancho Hernangomez':'Juan Hernangómez',
    'Willy Hernangomez':'Willy Hernangómez',
    'Ersan Ilyasova':'Ersan İlyasova',
    'Wes Iwundu':'Wesley Iwundu',
    'BJ Johnson':'B.J. Johnson',
    'Nikola Jokic':'Nikola Jokić',
    'Kevin Knox II':'Kevin Knox',
    'Skal Labissiere':'Skal Labissière',
    'Timothe Luwawu-Cabarrot':'Timothé Luwawu-Cabarrot',
    'Boban Marjanovic':'Boban Marjanović',
    'Frank Mason':'Frank Mason III',
    'Nicolo Melli':'Nicolò Melli',
    'CJ Miles':'C.J. Miles',
    'Dzanan Musa':'Džanan Musa',
    'Svi Mykhailiuk':'Sviatoslav Mykhailiuk',
    'Zach Norvell Jr.': 'Zach Norvell',
    'Jusuf Nurkic':'Jusuf Nurkić',
    'Anzejs Pasecniks':'Anžejs Pasečņiks',
    'Otto Porter Jr.':'Otto Porter',
    'Kristaps Porzingis':'Kristaps Porziņģis',
    'JJ Redick':'J.J. Redick',
    'Luka Samanic':'Luka Šamanić',
    'Dario Saric':'Dario Šarić',
    'Tomas Satoransky':'Tomáš Satoranský',
    'Dennis Schroder':'Dennis Schröder',
    'Alen Smailagic':'Alen Smailagić',
    'JR Smith':'J.R. Smith',
    'Jonas Valanciunas':'Jonas Valančiūnas',
    'Nikola Vucevic':'Nikola Vučević',
    'Lonnie Walker IV':'Lonnie Walker',
    'Derrick Walton Jr.':'Derrick Walton',
    'Robert Williams III':'Robert Williams',
    'Ante Zizic':'Ante Žižić',
    'Danuel House Jr.':'Danuel House',
    'Marcus Morris Sr.':'Marcus Morris'
}

In [157]:
for old_name, new_name in player_names_replacements.items():
    players_df.loc[players_df['player_name']==old_name, 'player_name'] = new_name

##### Perform the merge between s2020_df and players_df again, this time, without misses

In [158]:
df = s2020_df.merge(players_df, how='left', left_on='Player', right_on='player_name')

In [159]:
df['player_name'].isna().sum()

0

##### Remove unnecessary columns

In [160]:
columns_to_drop = [  
    "PER",
    "TS%",
    "3PAr",
    "FTr",
    "USG%",
    "OWS",
    "DWS",
    "WS",
    "WS/48",
    "OBPM",
    "DBPM",
    "BPM",
    "VORP",
    "player_name",
    'Unnamed: 0',
    'team_abbreviation',
    'age',
    'player_height',
    'player_weight',
    'season',
    'draft_year',
    'draft_round',
    'draft_number'
]

In [161]:
df.drop(columns=columns_to_drop, inplace=True)

##### Rename teams to their full name
Add a new column 'Team' to display their full name.

In [162]:
list(df['Tm'].unique())

['OKC',
 'MIA',
 'SAS',
 'NOP',
 'MEM',
 'BRK',
 'NYK',
 'ORL',
 'HOU',
 'MIL',
 'LAL',
 'POR',
 'TOR',
 'CHI',
 'TOT',
 'SAC',
 'PHO',
 'CHO',
 'DAL',
 'DEN',
 'MIN',
 'WAS',
 'ATL',
 'GSW',
 'LAC',
 'IND',
 'UTA',
 'PHI',
 'CLE',
 'DET',
 'BOS']

In [163]:
team_mapping = {
    'OKC':'Oklahoma City Thunder',
    'MIA':'Miami Heat',
    'SAS':'San Antonio Spurs',
    'NOP':'New Orleans Pelicans',
    'MEM':'Memphis Grizzlies',
    'BRK':'Brooklyn Nets',
    'NYK':'New York Knicks',
    'ORL':'Orlando Magic',
    'HOU':'Houston Rockets',
    'MIL':'Milwaukee Bucks',
    'LAL':'Los Angeles Lakers',
    'POR':'Portland Trail Blazers',
    'TOR':'Toronto Raptors',
    'CHI':'Chicago Bulls',
    'SAC':'Sacramento Kings',
    'PHO':'Phoenix Suns',
    'CHO':'Charlotte Hornets',
    'DAL':'Dallas Mavericks',
    'DEN':'Denver Nuggets',
    'MIN':'Minnesota Timberwolves',
    'WAS':'Washington Wizards',
    'ATL':'Atlanta Hawks',
    'GSW':'Golden State Warriors',
    'LAC':'Los Angeles Clippers',
    'IND':'Indiana Pacers',
    'UTA':'Utah Jazz',
    'PHI':'Philadelphia 76ers',
    'CLE':'Cleveland Cavaliers',
    'DET':'Detroit Pistons',
    'BOS':'Boston Celtics'
}

In [164]:
df['Team'] = df['Tm'].replace(team_mapping)

In [170]:
#Drop more redundant columns
col_to_drop = [
    'gp', 'oreb_pct', 'dreb_pct', 'ast_pct'
]

In [171]:
df.drop(columns=col_to_drop, inplace=True)

##### Delete all players from the TOT team
Finally, if you explore the dataset, you'll notice that there's a team TOT. In reality, that team doesn't exist, and it's just an aggregation for players that have switched teams in the season.

In [166]:
df.drop(df.loc[df['Tm'] == 'TOT'].index, inplace=True)

### Analysis

##### What's the team with the most players in the league?

In [172]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 591 entries, 0 to 650
Data columns (total 22 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Player      591 non-null    object
 1   Pos         591 non-null    object
 2   Age         591 non-null    int64
 3   Tm          591 non-null    object
 4   G           591 non-null    int64
 5   MP          591 non-null    int64
 6   ORB%        591 non-null    float64
 7   DRB%        591 non-null    float64
 8   TRB%        591 non-null    float64
 9   AST%        591 non-null    float64
 10  STL%        591 non-null    float64
 11  BLK%        591 non-null    float64
 12  TOV%        589 non-null    float64
 13  college     512 non-null    object
 14  country     591 non-null    object
 15  pts         591 non-null    float64
 16  reb         591 non-null    float64
 17  ast         591 non-null    float64
 18  net_rating  591 non-null    float64
 19  usg_pct     591 non-null    float64
 20  ts_pct      591 non-null    float64
 21  Team        591 non-null    object
dtypes: float64(13), int64(3), object(6)
memory usage: 106.2+ KB

In [167]:
df.groupby('Team')['Player'].size().sort_values(ascending=False).head()

Team
Brooklyn Nets             24
Minnesota Timberwolves    24
Washington Wizards        23
Sacramento Kings          23
Detroit Pistons           22
Name: Player, dtype: int64

##### Who are the top 5 highest-scoring players (pts) who have played at least 50 games (G), and what teams do they play for?

In [176]:
df.loc[df['G']>=50, ['Player','Team','pts']].sort_values('pts',ascending=False).head(5)

                    Player                    Team   pts
257           James Harden         Houston Rockets  34.3
40            Bradley Beal      Washington Wizards  30.5
376         Damian Lillard  Portland Trail Blazers  30.0
646             Trae Young           Atlanta Hawks  29.6
12   Giannis Antetokounmpo         Milwaukee Bucks  29.5

##### Which team (Team) has the highest average Net Rating (net_rating) across all their rostered players?

In [181]:
df.groupby('Team')['net_rating'].mean().sort_values(ascending=False).head(1)

Team
Toronto Raptors    7.027778
Name: net_rating, dtype: float64

##### Which colleges produced the most NBA players in this dataset?

In [183]:
df['college'].value_counts().head()

college
Kentucky          31
Duke              27
North Carolina    17
UCLA              16
Kansas            15
Name: count, dtype: int64

##### Which players are the true offensive engines — defined as having a Usage Percentage (usg_pct) over 25% AND a True Shooting Percentage (ts_pct) over 60%?

In [185]:
df.loc[(df['usg_pct']>0.25) & (df['ts_pct']>0.6), ['Player', 'usg_pct', 'ts_pct']].sort_values('usg_pct', ascending=False).head()

                    Player  usg_pct  ts_pct
12   Giannis Antetokounmpo    0.363   0.613
257           James Harden    0.356   0.626
68            Devin Booker    0.294   0.618
376         Damian Lillard    0.294   0.627
639        Zion Williamson    0.291   0.616

##### Which NBA teams rely the most on older, experienced players? Calculate the exact percentage of each team's roster that is made up of "Veterans" (players aged 30 or older).

In [186]:
veteran_summary =df.groupby('Team').agg({
    'Age': lambda x: (x>=30).mean() * 100
})

veteran_summary = veteran_summary.rename(columns={'Age': 'veteran_pct'})
veteran_summary.sort_values('veteran_pct', ascending=False).head()

                        veteran_pct
Team
Houston Rockets           47.619048
Milwaukee Bucks           47.058824
Los Angeles Lakers        40.000000
San Antonio Spurs         38.888889
Portland Trail Blazers    26.315789